// Centralized user-facing UI strings.
// Pure relocation: values must match the exact original wording. Do not reword.
// Import with: import { strings } from '@/constants/strings';

export const strings = {
  common: {
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    ok: 'OK',
    keep: 'Keep',
  },
  tabs: {
    expenses: 'Expenses',
    reports: 'Reports',
    categories: 'Categories',
    habits: 'Habits',
  },
  expenses: {
    recent: 'Recent',
    upcoming: 'Upcoming',
    merchantPlaceholder: 'Merchant (e.g. Starbucks)',
    notePlaceholder: 'Note (optional)',
    saveExpense: 'Save Expense',
    all: 'All',
    editAccessibilityLabel: (title: string, amountLabel: string) => `Edit ${title}, ${amountLabel}`,
  },
  upcoming: {
    emptyTitle: 'Nothing upcoming',
    emptySubtitle:
      'Mark an expense as recurring (weekly or monthly) and its next occurrence shows up here.',
    totalLabel: (windowDays: number) => `NEXT ${windowDays} DAYS`,
    recurringCount: (count: number) =>
      `${count} recurring ${count === 1 ? 'expense' : 'expenses'}`,
  },
  habits: {
    title: 'Your Habits',
    subtitle: (activeCount: number, streakSuffix: string) => `${activeCount} active${streakSuffix}`,
    streakSuffix: (streakTotal: number) => ` | ${streakTotal} day streak`,
    dollarsKept: 'DOLLARS KEPT',
    dollarsKeptCaption: "from the habits you're breaking",
    sectionInsights: 'Insights',
    sectionActiveChanges: 'Active Changes',
    sectionLearning: 'Learning',
    sectionBadgeNew: (count: number) => `${count} new`,
    loading: 'Analyzing your spending patterns...',
    emptyTitle: 'No habits detected yet',
    emptySubtitle:
      "Keep adding expenses and we'll identify your spending patterns automatically.",
    tip: 'Tip: Add at least 5 expenses at the same merchant to detect a habit.',
    // HabitProgressCard
    active: 'Active',
    reduceToAmount: (target: string) => `Reduce to ${target}/month`,
    reduceToFrequency: (target: number | undefined) => `Reduce to ${target}x/week`,
    eliminate: 'Eliminate this habit',
    substitute: (target: string | undefined) => `Replace with ${target}`,
    trackThisHabit: 'Track this habit',
    savingsProgress: 'Savings Progress',
    logToday: 'Log Today',
    // HabitInsightCard
    trackAction: 'Track',
    dismissAction: 'Dismiss',
    perMonth: 'per month',
    perDay: 'day',
    perWeek: 'week',
    perMonthUnit: 'month',
    perUnit: (unit: string) => `per ${unit}`,
    swipeHint: 'Swipe to track or dismiss',
  },
  // Habit logging v2 (docs/design-package-phase2/01-habit-logging-spec.md).
  // Vocabulary is load-bearing: skip is the win, slip is neutral and never
  // subtracts from Kept. Never reword to streak/success/completed language.
  habitLogging: {
    // Kept hero (4.1)
    keptSoFar: 'KEPT SO FAR',
    keptCaption: "money you didn't spend",
    // Leaks found section + leak card (4.10, unchanged from v1)
    leaksFoundSection: 'Leaks found',
    breakingNowSection: 'Breaking now',
    breakIt: 'Break it',
    notThisOne: 'Not this one',
    leakEvidence: (name: string, monthTotal: string, occurrences: number) =>
      `${name} costs you about ${monthTotal} a month. You bought it ${occurrences} times in the last 30 days.`,
    // Check-in card (4.2)
    dailyQuestion: 'Did you skip it today?',
    weeklyValueLine: (skipValue: string) => `Each skip keeps ${skipValue}.`,
    skipButton: (skipValue: string) => `Skipped it +${skipValue}`,
    skipOneButton: 'I skipped one',
    boughtItButton: 'I bought it',
    firstRunLine: 'Your first skip starts the counter.',
    weekSummaryBold: (n: number, m: number) => `${n} of ${m} days`,
    weekSummarySuffix: (weekKept: string | null) => ` skipped this week${weekKept ? ` · ${weekKept} kept` : ''}`,
    periodChip: (n: number) => `${n} skip${n === 1 ? '' : 's'} this week`,
    changeAnswer: 'Change answer',
    spentLessThanUsual: 'Spent less than usual?',
    // Confirmation slot (4.4)
    skipConfirmationDaily: (skipValue: string, n: number, m: number) =>
      `+${skipValue} kept. That's ${n} of ${m} days this week.`,
    skipConfirmationFirstEver: (skipValue: string) => `+${skipValue} kept. Your counter is running.`,
    skipConfirmationWeekly: (skipValue: string, n: number) => `+${skipValue} kept. ${n} skips this week.`,
    slipConfirmationDaily: (n: number, m: number, keptTotal: string) =>
      `Logged. Still ${n} of ${m} days this week. Your ${keptTotal} kept stays yours.`,
    slipConfirmationZero: 'Logged. Tomorrow is a fresh start.',
    slipConfirmationWeekly: (keptTotal: string) => `Logged. Your ${keptTotal} kept stays yours.`,
    changeToSlipConfirmation: (skipValue: string) =>
      `Corrected. Today is a slip, so ${skipValue} came off your kept total. It was never spent money, just today's answer.`,
    // Backfill (3.6)
    missedYesterday: 'Missed yesterday? Answer for it:',
    backfillSkip: 'Skipped it',
    backfillBought: 'Bought it',
    backfillYesterdaySkipped: (skipValue: string) => `Yesterday: skipped, +${skipValue} kept.`,
    backfillYesterdaySlipped: 'Yesterday: bought it. Recorded.',
    // Milestone / coach moment slot (4.5)
    milestoneHeadline: (n: number, chapter: string) => `${n} total skips · ${chapter}`,
    milestoneCardText: 'A new chapter. Progress here only accumulates, slips never subtract.',
    coachFirstSkip: 'Your counter is running. Every skip is money you decided to keep.',
    coachSkip: 'The urge passes in minutes. The money you kept stays all day.',
    coachSlip: 'Missing once is an accident. Missing twice starts a new habit.',
    // Pick-one sheet (4.3)
    pickOneCadenceDaily: 'A daily leak',
    pickOneCadenceWeekly: 'A weekly leak',
    pickOneCadenceMonthly: 'A monthly leak',
    pickOneValueLine: 'Each time you skip it, we count the money as kept.',
    pickOneFieldLabel: 'One skip keeps',
    pickOneCadenceNoteDaily: "We'll ask each day: did you skip it?",
    pickOneCadenceNoteEvent: 'Tap I skipped one whenever you skip. No daily check-in.',
    startBreakingIt: 'Start breaking it',
    freeTierNote: '1 habit on the free plan',
    freeTierTrialCta: 'Start a free trial',
    // Partial slip sheet (4.7)
    partialSheetTitle: 'How much did it cost?',
    partialSheetSubtitle: (skipValue: string) =>
      `You usually spend about ${skipValue}. Anything under that counts as kept.`,
    partialAmountLabel: 'Amount spent',
    partialConfirmation: (amount: string, skipValue: string, difference: string) =>
      `Logged. You spent ${amount} instead of ${skipValue}, so ${difference} counts as kept.`,
    partialConfirmationFreshStart: 'Logged. Fresh start tomorrow.',
    // Long arc (4.6)
    longArcTitle: 'The long arc',
    arcOf66: (total: number) => `${total}`,
    arcOf66Label: 'OF 66',
    arcSupportLine: (total: number) => `${total} skips toward the ~66 it takes to rewire a habit. Slips never subtract.`,
    chapterDeciding: 'Deciding',
    chapterRhythm: 'Rhythm',
    chapterCruising: 'Cruising',
    chapterRewiring: 'Rewiring',
    chapterRewired: 'Rewired',
    identityDeciding: "You're deciding where your money goes.",
    identityRhythm: "You're finding your rhythm.",
    identityCruising: "You're cruising. The habit is losing its grip.",
    identityRewiring: "You're almost rewired.",
    identityRewired: "Rewired. This habit doesn't run you anymore.",
    // Detail screen stats row (4.8)
    statKept: 'Kept',
    statThisWeek: 'This week',
    statThisWeekWeekly: (n: number) => `${n} skips`,
    statTotalSkips: 'Total skips',
    editSkipValue: (skipValue: string) => `Edit one skip keeps (${skipValue})`,
    stopBreakingHabit: 'Stop breaking this habit',
    stopBreakingConfirmTitle: 'Stop breaking this habit?',
    stopBreakingConfirmMessage: 'Your history is kept. You can start breaking it again any time.',
    // History calendar (4.9)
    legendSkipped: 'Skipped',
    legendSlipped: 'Slipped',
    legendNoLog: 'No log',
    eventSkippedOne: (skipValue: string) => `Skipped one · +${skipValue}`,
    eventBoughtIt: 'Bought it',
    eventBoughtItPartial: (difference: string) => `Bought it · ${difference} kept`,
    // Empty states (4.10)
    emptyLeaksTitle: 'No leaks found yet',
    emptyLeaksSubtitle: 'Keep logging expenses. Around 4 logs at the same place is enough to spot a pattern.',
    logAnExpense: 'Log an expense',
    keptZeroCaption: 'your first skip starts this counter',
  },
  habitDetail: {
    notFound: 'Habit not found',
    sentimentHabit: (sentiment: string) => `${sentiment} Habit`,
    perMonth: 'per month',
    perDay: 'day',
    perWeek: 'week',
    perMonthUnit: 'month',
    perUnit: (unit: string) => `per ${unit}`,
    whenDoesThisHappen: 'When Does This Happen?',
    confidence: (percent: number) => `${percent}% confidence`,
    yourProgress: 'Your Progress',
    savingsProgress: 'Savings Progress',
    ofGoal: (goal: string) => `of ${goal} goal`,
    milestones: 'Milestones',
    dayStreak: (target: number) => `${target} day streak`,
    suggestions: 'Suggestions',
    suggestionCoffee: 'Try preparing coffee at home to save on coffee shop visits.',
    suggestionReminder: 'Set a reminder before your usual spending time.',
    startTracking: 'Start Tracking This Habit',
    logging: 'Logging...',
    logTodayAsSuccess: 'Log Today as Success',
    slippedToday: 'I slipped today',
  },
  categories: {
    title: 'Categories',
    defaultCategories: 'Default Categories',
    customCategories: 'Custom Categories',
    loading: 'Loading categories...',
    emptyTitle: 'No categories yet',
    emptySubtitle: 'Tap the + button to add your first category',
    deleteTitle: 'Delete Category',
    deleteMessage: (name: string) =>
      `Are you sure you want to delete "${name}"? Your existing expenses are kept; they'll just no longer show this category.`,
    thisMonthSuffix: (amount: string) => `${amount} this month`,
  },
  categoryDetail: {
    notFound: 'Category not found',
    budget: (amount: string) => `Budget: ${amount}/month`,
    thisMonth: 'this month',
    vsLastMonth: (percent: number) => `${percent}% vs last month`,
    transactions: 'transactions',
    avgTransaction: 'avg transaction',
    sixMonthTrend: '6-Month Trend',
    topMerchants: 'Top Merchants',
    transactionCount: (count: number) => `${count} transaction${count !== 1 ? 's' : ''}`,
    recentTransactions: 'Recent Transactions',
    noTransactions: 'No transactions yet',
    transactionDate: (date: string, time: string) => `${date} at ${time}`,
  },
  reports: {
    title: 'Reports',
    subtitle: 'Your financial insights',
    loading: 'Loading reports...',
    total: 'Total',
    noSpendingData: 'No spending data',
    noActiveHabits: 'No active habits',
    projectedThisMonth: 'projected this month',
    spent: (amount: string) => `${amount} spent`,
    daysLeft: (days: number) => `${days} days left`,
    timeRangeWeek: '7D',
    timeRangeMonth: '30D',
    timeRangeQuarter: '3M',
    timeRangeYear: '1Y',
  },
  settings: {
    account: 'Account',
    profile: 'Profile',
    notifications: 'Notifications',
    preferences: 'Preferences',
    appearance: 'Appearance',
    currency: 'Currency',
    privacy: 'Privacy',
    about: 'About',
    version: 'Version',
    versionValue: '1.0.0',
    developer: 'Developer',
    resetOnboarding: 'Reset Onboarding',
    // Theme mode labels
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    // Currency alert
    currencyAlertTitle: 'Currency',
    currencyAlertMessage: 'Choose your currency',
    currencyOption: (name: string, symbol: string) => `${name} (${symbol})`,
    // Appearance alert
    appearanceAlertTitle: 'Appearance',
    appearanceAlertMessage: 'Choose theme',
    // Reset onboarding alert
    onboardingResetTitle: 'Onboarding Reset',
    onboardingResetMessage: 'Close and reopen the app to see the welcome screen.',
    restartNow: 'Restart Now',
  },
  addCategoryModal: {
    editCategory: 'Edit Category',
    newCategory: 'New Category',
    categoryNamePreview: 'Category Name',
    name: 'Name',
    namePlaceholder: 'Enter category name',
    icon: 'Icon',
    color: 'Color',
    monthlyBudget: 'Monthly Budget (Optional)',
    budgetPlaceholder: '0',
  },
  editExpenseModal: {
    cancelAccessibilityLabel: 'Cancel editing',
    title: 'Edit Expense',
    saveAccessibilityLabel: 'Save expense',
    category: 'Category',
    merchant: 'Merchant',
    merchantPlaceholder: 'Merchant (e.g. Starbucks)',
    note: 'Note',
    notePlaceholder: 'Note (optional)',
    keep: 'Keep',
    deleteExpense: 'Delete expense',
    confirmDeleteAccessibilityLabel: 'Confirm delete expense',
    deleteAccessibilityLabel: 'Delete expense',
  },
  // Onboarding (P2-1, docs/design-package-phase2/02-p2-1-onboarding-leak-audit.md).
  // Two-door fork + Door 1 Leak Audit, the v1 ship gate. Sentence case, no em
  // dashes; every amount below is a display example only, real amounts always
  // render via useCurrency().format.
  onboarding: {
    // 3.1 Welcome
    welcomeHeadline: (amount: string) => `Find the spending habit quietly costing you ${amount} a month`,
    welcomeSub: 'Everything stays on your phone. No bank login. No account.',
    findMyLeak: 'Find my leak',
    howItWorks: 'How it works',
    howItWorksSheet: "Log expenses in 10 seconds. We spot the habit that leaks the most. Every time you skip it, we count the money you kept.",
    // 3.2 Two-door fork
    forkTitle: 'How do you want to start?',
    forkSub: 'Both stay on this device.',
    doorFreshTag: 'About a minute',
    doorFreshName: 'Start fresh',
    doorFreshDescription: 'Tap through what you pay for. We estimate your leak from your answers.',
    doorStatementsTag: '2 to 3 minutes',
    doorStatementsName: 'Bring your statements',
    doorStatementsDescription: 'Import a bank CSV. We scan it on your phone. Nothing uploads, ever.',
    skipForNow: 'Skip for now',
    // 3.3 Step 1: auto-pilot charges
    step1Eyebrow: 'Step 1 of 2 · about 30 seconds',
    step1Title: 'Which of these charge you on auto-pilot?',
    step1Sub: "Tap the ones that ring a bell, we'll watch them for you. A quick scan, not a full inventory. Tap a price to make it exact.",
    somethingElse: 'Something else',
    somethingElseYouSetIt: 'you set it',
    somethingElseNamePlaceholder: 'What is it called?',
    runningTotalMonth: (total: string) => `${total} a month so far`,
    continueButton: 'Continue',
    noneOfThese: 'None of these',
    editorRealPrice: (chipName: string) => `${chipName} · your real price`,
    editorPresetCaption: (preset: string) =>
      `Preset was ${preset}. Set saves your exact price, ✕ keeps the preset.`,
    editorSet: 'Set',
    editorCancelLabel: 'Keep the preset price',
    // 3.4 Step 2: everyday rhythm
    step2Eyebrow: 'Step 2 of 2 · about 30 seconds',
    step2Title: 'And the everyday stuff?',
    step2Sub: 'Roughly how often in a typical week. No amounts to add up. Tap a price if yours differs.',
    eachAmount: (amount: string) => `about ${amount} each`,
    bandNever: 'Never',
    bandOneToTwo: '1-2',
    bandThreeToFive: '3-5',
    bandDaily: 'Daily',
    runningWeekly: (weekly: string) => `adds ${weekly} a week`,
    seeMyLeak: 'See my leak',
    skipThisStep: 'Skip this step',
    // 3.5 The reveal
    revealYearly: (yearly: string) => `~${yearly}`,
    revealCaption: (monthly: string) => `leaking a year. That's about ${monthly} a month.`,
    revealCaptionSubsOnly: (monthly: string) =>
      `leaking a year from your subscriptions so far. That's about ${monthly} a month.`,
    breakdownLine: (source: string, amount: string) => `${source} · ~${amount}/yr`,
    revealHonesty: 'A starting estimate from one minute of taps, not a judgment. Real logs sharpen it from here.',
    plugBiggestLeak: 'Plug the biggest leak',
    justStartLogging: 'Just start logging',
    revealAnnouncement: (yearly: string, monthly: string) =>
      `About ${yearly} a year leaking, about ${monthly} a month`,
    // Both-empty edge case (section 8)
    noNumberYetTitle: "We'll find your leak from your real logs.",
    noNumberYetSubtitle: 'Around 4 logs at the same place is enough to spot a pattern.',
    // 3.6 Guided first log
    guidedLogHint: "One practice log and you're done. Try today's coffee. Amount first.",
    guidedLogLater: 'Later',
    // 3.7 Success
    leakMapReady: 'Your leak map is ready',
    biggestLeakCaption: (monthTotal: string) => `about ${monthTotal} a month · your biggest leak`,
    breakIt: 'Break it',
    trialQuietNote: "1 habit free, always. Premium trial available when you're ready.",
    continueToHabits: 'Continue',
    // Re-entry (section 7, Habits empty-state link)
    reAuditLink: 'Take the 90-second leak audit',
    // Door 2 graceful-failure re-entry (section 8.6): scan-found chips are
    // pre-selected at exact values, no tilde, annotated.
    fromYourStatements: 'from your statements',
  },
} as const;
