// Centralized user-facing UI strings.
// Pure relocation: values must match the exact original wording. Do not reword.
// Import with: import { strings } from '@/constants/strings';

export const strings = {
  common: {
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    ok: 'OK',
    keep: 'Keep',
  },
  tabs: {
    expenses: 'Expenses',
    reports: 'Reports',
    categories: 'Categories',
    habits: 'Habits',
  },
  expenses: {
    recent: 'Recent',
    upcoming: 'Upcoming',
    merchantPlaceholder: 'Merchant (e.g. Starbucks)',
    notePlaceholder: 'Note (optional)',
    saveExpense: 'Save Expense',
    all: 'All',
    editAccessibilityLabel: (title: string, amountLabel: string) => `Edit ${title}, ${amountLabel}`,
  },
  upcoming: {
    emptyTitle: 'Nothing upcoming',
    emptySubtitle:
      'Mark an expense as recurring (weekly or monthly) and its next occurrence shows up here.',
    totalLabel: (windowDays: number) => `NEXT ${windowDays} DAYS`,
    recurringCount: (count: number) =>
      `${count} recurring ${count === 1 ? 'expense' : 'expenses'}`,
  },
  habits: {
    title: 'Your Habits',
    subtitle: (activeCount: number, streakSuffix: string) => `${activeCount} active${streakSuffix}`,
    streakSuffix: (streakTotal: number) => ` | ${streakTotal} day streak`,
    dollarsKept: 'DOLLARS KEPT',
    dollarsKeptCaption: "from the habits you're breaking",
    sectionInsights: 'Insights',
    sectionActiveChanges: 'Active Changes',
    sectionLearning: 'Learning',
    sectionBadgeNew: (count: number) => `${count} new`,
    loading: 'Analyzing your spending patterns...',
    emptyTitle: 'No habits detected yet',
    emptySubtitle:
      "Keep adding expenses and we'll identify your spending patterns automatically.",
    tip: 'Tip: Add at least 5 expenses at the same merchant to detect a habit.',
    // HabitProgressCard
    active: 'Active',
    reduceToAmount: (target: string) => `Reduce to ${target}/month`,
    reduceToFrequency: (target: number | undefined) => `Reduce to ${target}x/week`,
    eliminate: 'Eliminate this habit',
    substitute: (target: string | undefined) => `Replace with ${target}`,
    trackThisHabit: 'Track this habit',
    savingsProgress: 'Savings Progress',
    logToday: 'Log Today',
    // HabitInsightCard
    trackAction: 'Track',
    dismissAction: 'Dismiss',
    perMonth: 'per month',
    perDay: 'day',
    perWeek: 'week',
    perMonthUnit: 'month',
    perUnit: (unit: string) => `per ${unit}`,
    swipeHint: 'Swipe to track or dismiss',
  },
  habitDetail: {
    notFound: 'Habit not found',
    sentimentHabit: (sentiment: string) => `${sentiment} Habit`,
    perMonth: 'per month',
    perDay: 'day',
    perWeek: 'week',
    perMonthUnit: 'month',
    perUnit: (unit: string) => `per ${unit}`,
    whenDoesThisHappen: 'When Does This Happen?',
    confidence: (percent: number) => `${percent}% confidence`,
    yourProgress: 'Your Progress',
    savingsProgress: 'Savings Progress',
    ofGoal: (goal: string) => `of ${goal} goal`,
    milestones: 'Milestones',
    dayStreak: (target: number) => `${target} day streak`,
    suggestions: 'Suggestions',
    suggestionCoffee: 'Try preparing coffee at home to save on coffee shop visits.',
    suggestionReminder: 'Set a reminder before your usual spending time.',
    startTracking: 'Start Tracking This Habit',
    logging: 'Logging...',
    logTodayAsSuccess: 'Log Today as Success',
    slippedToday: 'I slipped today',
  },
  categories: {
    title: 'Categories',
    defaultCategories: 'Default Categories',
    customCategories: 'Custom Categories',
    loading: 'Loading categories...',
    emptyTitle: 'No categories yet',
    emptySubtitle: 'Tap the + button to add your first category',
    deleteTitle: 'Delete Category',
    deleteMessage: (name: string) =>
      `Are you sure you want to delete "${name}"? Your existing expenses are kept; they'll just no longer show this category.`,
    thisMonthSuffix: (amount: string) => `${amount} this month`,
  },
  categoryDetail: {
    notFound: 'Category not found',
    budget: (amount: string) => `Budget: ${amount}/month`,
    thisMonth: 'this month',
    vsLastMonth: (percent: number) => `${percent}% vs last month`,
    transactions: 'transactions',
    avgTransaction: 'avg transaction',
    sixMonthTrend: '6-Month Trend',
    topMerchants: 'Top Merchants',
    transactionCount: (count: number) => `${count} transaction${count !== 1 ? 's' : ''}`,
    recentTransactions: 'Recent Transactions',
    noTransactions: 'No transactions yet',
    transactionDate: (date: string, time: string) => `${date} at ${time}`,
  },
  reports: {
    title: 'Reports',
    subtitle: 'Your financial insights',
    loading: 'Loading reports...',
    total: 'Total',
    noSpendingData: 'No spending data',
    noActiveHabits: 'No active habits',
    projectedThisMonth: 'projected this month',
    spent: (amount: string) => `${amount} spent`,
    daysLeft: (days: number) => `${days} days left`,
    timeRangeWeek: '7D',
    timeRangeMonth: '30D',
    timeRangeQuarter: '3M',
    timeRangeYear: '1Y',
  },
  settings: {
    account: 'Account',
    profile: 'Profile',
    notifications: 'Notifications',
    preferences: 'Preferences',
    appearance: 'Appearance',
    currency: 'Currency',
    privacy: 'Privacy',
    about: 'About',
    version: 'Version',
    versionValue: '1.0.0',
    developer: 'Developer',
    resetOnboarding: 'Reset Onboarding',
    // Theme mode labels
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    // Currency alert
    currencyAlertTitle: 'Currency',
    currencyAlertMessage: 'Choose your currency',
    currencyOption: (name: string, symbol: string) => `${name} (${symbol})`,
    // Appearance alert
    appearanceAlertTitle: 'Appearance',
    appearanceAlertMessage: 'Choose theme',
    // Reset onboarding alert
    onboardingResetTitle: 'Onboarding Reset',
    onboardingResetMessage: 'Close and reopen the app to see the welcome screen.',
    restartNow: 'Restart Now',
  },
  addCategoryModal: {
    editCategory: 'Edit Category',
    newCategory: 'New Category',
    categoryNamePreview: 'Category Name',
    name: 'Name',
    namePlaceholder: 'Enter category name',
    icon: 'Icon',
    color: 'Color',
    monthlyBudget: 'Monthly Budget (Optional)',
    budgetPlaceholder: '0',
  },
  editExpenseModal: {
    cancelAccessibilityLabel: 'Cancel editing',
    title: 'Edit Expense',
    saveAccessibilityLabel: 'Save expense',
    category: 'Category',
    merchant: 'Merchant',
    merchantPlaceholder: 'Merchant (e.g. Starbucks)',
    note: 'Note',
    notePlaceholder: 'Note (optional)',
    keep: 'Keep',
    deleteExpense: 'Delete expense',
    confirmDeleteAccessibilityLabel: 'Confirm delete expense',
    deleteAccessibilityLabel: 'Delete expense',
  },
  welcome: {
    logo: 'HabitCents',
    tagline: 'Track your spending\nwith voice or text',
    description: 'See where your money goes with clear insights and easy expense tracking.',
    getStarted: 'Get Started',
    skipForNow: 'Skip for now',
  },
  onboarding: {
    // welcome.tsx
    title: 'HabitCents',
    tagline: 'Build better spending habits,\none cent at a time',
    featureTrack: 'Track expenses instantly',
    featureDiscover: 'Discover spending patterns',
    featureBuild: 'Build lasting habits',
    getStarted: 'Get Started',
    // value.tsx
    quickTrackingTitle: 'Quick Tracking',
    quickTrackingDescription: 'Add expenses in seconds. Just enter the amount and category - done!',
    smartInsightsTitle: 'Smart Insights',
    smartInsightsDescription: 'We automatically detect your spending habits and patterns over time.',
    buildBetterHabitsTitle: 'Build Better Habits',
    buildBetterHabitsDescription: 'Set goals, track streaks, and celebrate wins. Small changes add up!',
    skip: 'Skip',
    letsGo: "Let's Go",
    next: 'Next',
    // first-expense.tsx
    food: 'Food',
    shopping: 'Shopping',
    entertainment: 'Entertainment',
    transportation: 'Transportation',
    firstExpenseTitle: 'Add your first expense',
    firstExpenseSubtitle: 'This only takes a few seconds - try it out!',
    whatWasItFor: 'What was it for?',
    saveExpense: 'Save Expense',
    // success.tsx
    allSet: "You're all set!",
    successSubtitle: "Your first expense has been saved.\nLet's start building better habits.",
  },
} as const;
